### PR TITLE
Fix problem with newline in vocab files

### LINKED ISSUE #519: vocab file in UCI bow require \n in the last line
In python users might choose to export vocab file as follows:
```
"\n".join(words)
```
This won't work because currently the UCI bow parser in BigARTM core require a `\n` also in the last line. So python script must have something like this: ``"\n".join(words) + "\n"``, which is really ugly.
We should fix the parser to properly read the last line without \n.

### PR DESCRIPTION
**Pull request by JeanPaulShapo**
@ofrei
* this PR indents to fix #519;
* new vocab file must be without the last newline;
* is it good idea to have identical code in `src/artm/core/dicitonary.cc` and `src/artm/core/collection_parser.cc`?

### CODE REVIEW

File: src/artm/core/dictionary.cc [hunk 1]
```diff
@@ -256,7 +256,7 @@ Dictionary::Gather(const GatherDictionaryArgs& args,
       int token_id = 0;
       while (!vocab.eof()) {
         std::getline(vocab, str);
-        if (vocab.eof())
+        if (vocab.eof() && str.empty())
```
Comment (ofrei) [inline src/artm/core/dictionary.cc]: Looks good!

File: src/artm/core/dictionary.cc [hunk 2]
```diff
@@ -545,3 +545,4 @@ float Dictionary::CountTopicCoherence(const std::vector<core::Token>& tokens_to_
 
 }  // namespace core
 }  // namespace artm
+// vim: set ts=2 sw=2:
```
Comment (ofrei) [inline src/artm/core/dictionary.cc]: >// vim: set ts=2 sw=2:
Is this intentional?

File: src/artm_tests/collection_parser_test.cc [hunk 3]
```diff
@@ -46,36 +46,48 @@ TEST(CollectionParser, UciBagOfWords) {
...
+    ASSERT_APPROX_EQ(dict.token_value(0), 5.0 / 18.0);
+    ASSERT_APPROX_EQ(dict.token_value(1), 2.0 / 9.0);
+    ASSERT_APPROX_EQ(dict.token_value(2), 0.5);
+  };
 
-  ASSERT_APPROX_EQ(dictionary.token_value(0), 5.0 / 18.0);
-  ASSERT_APPROX_EQ(dictionary.token_value(1), 2.0 / 9.0);
-  ASSERT_APPROX_EQ(dictionary.token_value(2), 0.5);
+  dictionary_checker(config.vocab_file_path(), "default_dictionary");
+  dictionary_checker("../../../test_data/vocab.parser_test_no_newline.txt", "no_newline_dictionary");
```
Comment (ofrei) [inline src/artm_tests/collection_parser_test.cc]: >../../../test_data/vocab.parser_test_no_newline.txt
``../../..`` in C++ tests is a bad practice, but I see it is used across multiple tests. So feel free to keep this code like this, but if you have time it would be nice to replace replace ``../../../test_data`` with BIGARTM_UNITTEST_DATA env variable. I think that should work, because we anyway have to set this variable for python tests.


It is unfortunate that we start filenames with ``../../..``,

**Comment by ofrei** [comment]
>new vocab file must be without the last newline;
My assumption is that both formats are valid -- both with and without the last newline. Is this the case, or actually "new vocab file **must** be without the last newline;"?

**Comment by JeanPaulShapo** [comment]
@ofrei I crafted it to be **without** the last newline, and in test I checked both files - the old **with** newline and the new **without** newline.
I hope no one will edit this file to add newline.

File: src/artm/core/dictionary.cc (hunk 2 above)
Comment (JeanPaulShapo) [inline src/artm/core/dictionary.cc]: Yes, with additions in `.gitignore`.

**Comment by ofrei** [comment]
Ah, I see - if you mean the new test file (``test_data/vocab.parser_test_no_newline.txt``) - sure, it must be without the new line. Thanks for adding a test for this!

**Comment by ofrei** [comment]
>is it good idea to have identical code in `src/artm/core/dicitonary.cc` and `src/artm/core/collection_parser.cc`?
Yes, it's good to keep these two files consistent. Sad that they are copy-pasted like this.

**Comment by JeanPaulShapo** [comment]
I only wonder whether it's good idea to utilize this code in separate function
In that case we only need to fix bugs in one place.

**Comment by ofrei** [comment]
If you could refactor this code to avoid duplication - sure, that would be great.

**Comment by JeanPaulShapo** [comment]
Not in this PR.

**Comment by ofrei** [comment]
Agree)

**Comment by ofrei** [comment]
Sorry, I didn't put [PR:review OK]. You are welcome to fix any of the comments, but in either case this PR is good -- feel free to merge.

**Comment by JeanPaulShapo** [comment]
Whoops, I clicked the wrong button
